name: CI Pipeline

on:
  push:
    branches: [dev, prod]
  pull_request:
    branches: [dev, prod]

jobs:
  lint:
    name: Lint y formato de código
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar Ruff
        run: pip install ruff

      - name: Ejecutar Ruff (linting)
        run: ruff check . --output-format=full --show-fixes --statistics || true

      - name: Verificar formato
        run: ruff format --check --diff . || true

  database:
    name: Verificación de esquema de base de datos
    runs-on: ubuntu-latest
    services:
      postgres:    # GitHub Actions levanta un contenedor PostgreSQL temporal
        image: postgres:16  # Se descarga la imagen, crea el contenedor
        env:
          POSTGRES_USER: test_user #Usuario de prueba para el testeo de squemas
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: tilinflex_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user -d tilinflex_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Crear esquema y verificar tablas
        env:
          DATABASE_URL: postgresql://test_user:test_password@localhost:5432/tilinflex_test
          DB_SSLMODE: disable
        run: python -m scripts.verify_db

  docker:
    name: Build de imagen Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build de imagen Docker
        run: docker build -f docker/Dockerfile -t tilinflex-backend:ci .
#El contenedor se destruye automáticamente al finalizar el job, por lo que no es necesario agregar un paso para eliminarlo.
